name: itemChanger
version: 1.0.0
main: ch.hatbe2113.itemChanger.main.Main
description: itemChanger
author: hatbe2113
website: https://hatbe.ch
api-version: 1.16

commands:
   ichange:
      description: changes a Item
      aliases: ic